export const GENRE_IDS = {
  ACTION: 28,
  ADVENTURE: 12,
  ANIMATION: 16,
  COMEDY: 35,
  CRIME: 80,
  DOCUMENTARY: 99,
  DRAMA: 18,
  FAMILY: 10751,
  FANTASY: 14,
  HISTORY: 36,
  HORROR: 27,
  MUSIC: 10402,
  MYSTERY: 9648,
  ROMANCE: 10749,
  SCIENCE_FICTION: 878,
  TV_MOVIE: 10770,
  THRILLER: 53,
  WAR: 10752,
  WESTERN: 37,
  ACTION_ADVENTURE: 10759,
  KIDS: 10762,
  NEWS: 10763,
  REALITY: 10764,
  SCI_FI_FANTASY: 10765,
  SOAP: 10766,
  TALK: 10767,
  WAR_POLITICS: 10768,
};

export const GENRE_ID_TO_NAME: Record<number, string> = {
  [GENRE_IDS.ACTION]: 'Action',
  [GENRE_IDS.ADVENTURE]: 'Adventure',
  [GENRE_IDS.ANIMATION]: 'Animation',
  [GENRE_IDS.COMEDY]: 'Comedy',
  [GENRE_IDS.CRIME]: 'Crime',
  [GENRE_IDS.DOCUMENTARY]: 'Documentary',
  [GENRE_IDS.DRAMA]: 'Drama',
  [GENRE_IDS.FAMILY]: 'Family',
  [GENRE_IDS.FANTASY]: 'Fantasy',
  [GENRE_IDS.HISTORY]: 'History',
  [GENRE_IDS.HORROR]: 'Horror',
  [GENRE_IDS.MUSIC]: 'Music',
  [GENRE_IDS.MYSTERY]: 'Mystery',
  [GENRE_IDS.ROMANCE]: 'Romance',
  [GENRE_IDS.SCIENCE_FICTION]: 'Science Fiction',
  [GENRE_IDS.TV_MOVIE]: 'TV Movie',
  [GENRE_IDS.THRILLER]: 'Thriller',
  [GENRE_IDS.WAR]: 'War',
  [GENRE_IDS.WESTERN]: 'Western',
  [GENRE_IDS.ACTION_ADVENTURE]: 'Action & Adventure',
  [GENRE_IDS.KIDS]: 'Kids',
  [GENRE_IDS.NEWS]: 'News',
  [GENRE_IDS.REALITY]: 'Reality',
  [GENRE_IDS.SCI_FI_FANTASY]: 'Sci-Fi & Fantasy',
  [GENRE_IDS.SOAP]: 'Soap',
  [GENRE_IDS.TALK]: 'Talk',
  [GENRE_IDS.WAR_POLITICS]: 'War & Politics',
};

export const getGenreNameById = (genreId: number): string | undefined => {
  return GENRE_ID_TO_NAME[genreId];
};
